package com.example.bookworm;

import androidx.annotation.NonNull;
import androidx.fragment.app.FragmentActivity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.widget.Toast;

import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.MarkerOptions;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.firestore.QueryDocumentSnapshot;
import com.google.firebase.firestore.QuerySnapshot;

/**
 * Display the meeting location for an accepted request
 */
public class BorrowerMapActivity extends FragmentActivity implements OnMapReadyCallback {

    private GoogleMap mMap;
    private String selectedBookIsbn;
    private Request selectedRequest;
    private Context context = this;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_borrower_map);
        // Obtain the SupportMapFragment and get notified when the map is ready to be used.
        SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.map);
        mapFragment.getMapAsync(this);

        Intent intent = getIntent();
        selectedBookIsbn = intent.getStringExtra("isbn");

        // get the corresponding accepted request and display the latitude and longitude coordinates
        // with a marker
        Database.getAcceptedBooks()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot queryDocumentSnapshots) {
                        for (QueryDocumentSnapshot doc : queryDocumentSnapshots) {
                            //convert QuerySnapshot to a request object
                            Request request = doc.toObject(Request.class);
                            if (request.getBook().getIsbn().equals(selectedBookIsbn)) {
                                selectedRequest = request;
                                LatLng location = new LatLng(selectedRequest.getLat(),
                                        selectedRequest.getLng());
                                mMap.addMarker(new MarkerOptions()
                                        .position(location).title("Meeting location"));
                                mMap.moveCamera(CameraUpdateFactory.newLatLng(location));
                                Toast.makeText(context,
                                        "Here is the meeting location.",
                                        Toast.LENGTH_LONG).show();
                                break;
                            }
                        }
                    }
                })
                .addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Toast.makeText(context,
                                "Could not load the request. Please try again.",
                                Toast.LENGTH_LONG).show();
                        finish();
                    }
                });
    }

    /**
     * method generated by the Googlemap activity template
     * @param googleMap
     */
    @Override
    public void onMapReady(GoogleMap googleMap) {
        mMap = googleMap;
    }
}